In [1]:
# Import required libraries :
import numpy as np

In [2]:
# Define input features :
input_features = np.array([[0,0],[0,1],[1,0],[1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
# Define target output :
target_output = np.array([[0,1,1,1]])
# Reshaping our target output into vector :
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
# Define weights :
# 6 for hidden layer
# 3 for output layer
# 9 total
weight_hidden = np.array([[0.1,0.2,0.3], [0.4,0.5,0.6]])
weight_output = np.array([[0.7],[0.8],[0.9]])
# Learning Rate :
lr = 0.05

Once we have our weight values and input features, we are going to send it to the main function that predicts the output. Notice that our input features and weight values can be anything, but here we want to classify data, so we need the output between 0 and 1. For such output, we are going to use a sigmoid function.

In [5]:
# Sigmoid function :
def sigmoid(x):
    return 1/(1+np.exp(-x))

In a gradient descent algorithm, we need the derivative of the sigmoid function.

In [6]:
# Derivative of sigmoid function :
def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

The main logic for predicting output and updating the weight values:

In [7]:
for epoch in range(200000):
    # Input for hidden layer :
    input_hidden = np.dot(input_features, weight_hidden)

    # Output from hidden layer :
    output_hidden = sigmoid(input_hidden)

    # Input for output layer :
    input_op = np.dot(output_hidden, weight_output)

    # Output from output layer :
    output_op = sigmoid(input_op)

    #==========================================================
    # Phase1

    # Calculating Mean Squared Error :
    error_out = ((1 / 2) * (np.power((output_op - target_output), 2)))
    # print(error_out.sum())

    # Derivatives for phase 1 :
    derror_douto = output_op - target_output
    douto_dino = sigmoid_der(input_op)
    dino_dwo = output_hidden

    derror_dwo = np.dot(dino_dwo.T, derror_douto * douto_dino)

    #===========================================================
    # Phase 2
    # derror_w1 = derror_douth * douth_dinh * dinh_dw1
    # derror_douth = derror_dino * dino_outh

    # Derivatives for phase 2 :
    derror_dino = derror_douto * douto_dino
    dino_douth = weight_output
    derror_douth = np.dot(derror_dino , dino_douth.T)
    douth_dinh = sigmoid_der(input_hidden)
    dinh_dwh = input_features
    derror_wh = np.dot(dinh_dwh.T, douth_dinh * derror_douth)

    # Update Weights
    weight_hidden -= lr * derror_wh
    weight_output -= lr * derror_dwo

In [8]:
# Final hidden layer weight values :
print (weight_hidden)

[[-3.82270773  2.36324803  3.13867107]
 [-3.79490945  2.45183148  3.18541383]]


In [9]:
# Final output layer weight values :
print (weight_output)

[[-13.22689481]
 [  1.74391783]
 [  3.50426502]]


Predictions :

In [10]:
#Taking inputs :
single_point = np.array([1,1])
#1st step :
result1 = np.dot(single_point, weight_hidden)
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

[0.99462917]


In [11]:
#Taking inputs :
single_point = np.array([0,0])
#1st step :
result1 = np.dot(single_point, weight_hidden)
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

[0.01817518]


In [12]:
#Taking inputs :
single_point = np.array([1,0])
#1st step :
result1 = np.dot(single_point, weight_hidden)
#2nd step :
result2 = sigmoid(result1)
#3rd step :
result3 = np.dot(result2,weight_output)
#4th step :
result4 = sigmoid(result3)
print(result4)

[0.99071056]
