In [1]:
import numpy as np

In [2]:
# define input features:
input_features = np.array([[0,0], [0,1], [1,0], [1,1]])
print(input_features.shape)
input_features

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
# define target output:
target_output = np.array([[0,1,1,1]])

# reshaping out target output into vector:
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
# define weights:
# because have two input features
weights = np.array([[0.1], [0.2]])
print(weights.shape)
weights

(2, 1)


array([[0.1],
       [0.2]])

In [5]:
# The value of bias = 1
# bias weight:
bias = 0.3
# learning rate:
lr = 0.05

In [6]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
# Derivative of sigmoid function
def sigmoid_der(x):
    return sigmoid(x) * (1-sigmoid(x))

In [8]:
# Running our code 10000 times:
for epoch in range(10000):
    inputs = input_features

    # Feedforward input:
    in_o = np.dot(inputs, weights) + bias

    # Feedforward output:
    out_o = sigmoid(in_o)

    # Backpropogation
    # Calculating error
    error = out_o - target_output

    #G oing with the formula:
    x = error.sum()
    # print(x)

    # Calculating derivative:
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives:
    deriv = derror_douto * douto_dino

    # Multiplying with the 3rd individual derivative:
    # Finding the transpose of input_features:
    inputs = input_features.T
    deriv_final = np.dot(inputs, deriv)

    # Updating the weights values:
    weights -= lr * deriv_final

    # Updating the bias weight value:
    for i in deriv:
        bias -= lr * i

In [9]:
#Check the final values for weight and bias
print (weights)
print (bias)

[[7.00922425]
 [7.00953281]]
[-3.14905135]


In [10]:
#Taking inputs:
single_point = np.array([1,0])

#1st step:
result1 = np.dot(single_point, weights) + bias

#2nd step:
result2 = sigmoid(result1)

#Print final result
print(result2)

[0.9793702]


In [11]:
#Taking inputs:
single_point = np.array([1,1])

#1st step:
result1 = np.dot(single_point, weights) + bias

#2nd step:
result2 = sigmoid(result1)

#Print final result
print(result2)

[0.99998097]


In [12]:
#Taking inputs:
single_point = np.array([0,0])

#1st step:
result1 = np.dot(single_point, weights) + bias

#2nd step:
result2 = sigmoid(result1)

#Print final result
print(result2)

[0.04112867]
